name: Grading workflow

on:
  registry_package:
    types: [published]

jobs:
  grade-learner:
    runs-on: ubuntu-latest
    steps:
      - name: troubleshooting steps
        run: echo "github event name is - ${{github.event_name}}" 
