name: Check Markdown links

on: push

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    if: github.repository == 'iarindam/github-action-handson-module-three'
    steps:
      - uses: actions/checkout@master
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
      - name: Build and Publish     
        run: |
          npm install
          npm run build --if-present
          npm login --scope=@iarindam --userconfig=./.npmrc --registry=https://registry.mycorp.com
          npm publish
        working-directory: ./sample-packages/npm
        shell: bash
